# Mogadishu S-Entropy Framework - Development Configuration

[development]
# Enable development features
debug_mode = true
verbose_logging = true
hot_reload = true

# S-entropy framework settings
[s_entropy]
default_viability_threshold = 10000.0
enable_miracle_tracing = true
observer_debug = true

# Cellular architecture settings  
[cellular]
atp_system_debug = true
membrane_quantum_tracing = true
dna_consultation_logging = true
oxygen_enhancement_debug = true

# Miraculous dynamics settings
[miraculous]
enable_impossibility_cache = true
reverse_causality_debug = true
miracle_optimization_verbose = true

# Bioreactor settings
[bioreactor]
cellular_observer_count = 100  # Reduced for development
coordination_debug = true
precision_difference_tracing = true

# Python integration
[python]
demo_auto_reload = true
plot_interactive = true
jupyter_auto_start = false
validation_verbose = true

# Development tools
[dev_tools]
cargo_watch_enabled = true
rust_analyzer_enabled = true
clippy_pedantic = true
format_on_save = true

# Logging configuration
[logging]
level = "debug"
targets = [
    "mogadishu::s_entropy",
    "mogadishu::cellular", 
    "mogadishu::miraculous",
    "mogadishu::bioreactor"
]

# Performance settings for development
[performance]
parallel_cellular_processing = false  # Easier debugging
optimization_level = "dev"
enable_simd = false

# Testing configuration
[testing]
quick_tests_only = false
generate_test_data = true
validate_against_theory = true
benchmark_comparisons = true
